### ISSUE TITLE
Repeatable fields

### ISSUE THREAD

**Issue by dlzi** [miharekar/mr-meta-box#2]
Is it possible to have reusable/repeatable fields or groups of fields?

**Comment by miharekar** [comment]
There are no repeatable fields yet since when I was thinking about it I couldn't really decide how I would want it to work. What exactly do you want / do you know how would you want that?

As for groups of fields you can make as many metaboxes as you need and it groups it nicely.

**Comment by dlzi** [comment]
Thanks for your quick answer. 

I'm working on a Slider (http://jacksbox.de/stuff/jquery-fractionslider/) and I need to have a repeatable group/block of 10 fields. Those fields are text, select and image fields. Each field represent a variable that controls an element options. It needs to be repeatable because each group represent one element of the slide. For example. If I want to have an image background and two captions easing in on one slide. I will need three blocks of those fields. I hope i made myself clear.

**Comment by miharekar** [comment]
Oh yeah, I understand what you want. No, unfortunately mr meta box can not (yet) do that. Try [My Meta Box](https://github.com/bainternet/My-Meta-Box) by @bainternet
