### ISSUE TITLE
I need an empty field

### ISSUE THREAD

**Issue by ghost** [miharekar/mr-meta-box#3]
Is it possible to create an empty field. I mean a field without an input field. Only an title and a text field or paragraph. 

I need that because to preview an shortcode, so the client can copy that. If there is an other option i love to hear that!

**Comment by miharekar** [comment]
So you would need a disabled text field? I don't think I understand you completely. Could you give me an example or a screenshot of what exactly you want and how would you use that with meta boxes?

**Comment by ghost** [comment]
Check the screenshot!
![empty-meta-box](https://f.cloud.github.com/assets/3524051/722808/0b4b4834-e009-11e2-8c45-c968681ed3f4.jpg)

It is just an Meta box with only an text description.

**Comment by miharekar** [comment]
Well you can easily achieve that without any library - it's just text. Meta boxes are kinda difficult to set up for form reading/posting, but placing static text in them is dead simple and so I will not make that a part of mr-meta-box.

**Comment by ghost** [comment]
Thanks! I understand!
