### ISSUE TITLE
Attached image field not returning src at frontend 

### ISSUE THREAD

**Issue by vivinblack** [miharekar/mr-meta-box#8]
Other metabox fields working properly but while dealing with image metabox field , images getting attached at metabox admin , but while calling it at frontend  using get_post_meta($post->ID, 'prefix_image', true);   its giving a digit number instead returning image src url.

**Comment by miharekar** [comment]
Yup, that's normal. You get the id, and then with that id you need to get the image from the media library. With [`wp_get_attachment_image_src`](https://developer.wordpress.org/reference/functions/wp_get_attachment_image_src/) for example. Similar to what I do on the [backend](https://github.com/mrfoto/mr-meta-box/blob/223998eb70288cce04a41ad6337116bae3376a9e/mr-meta-box.php#L310-L326).

**Comment by vivinblack** [comment]
Ohh ! How dumb I am ,Image field returns attachment ID and not the attachment URL directly , got it.

**Comment by miharekar** [comment]
Happens to all of us :smile:
